### ISSUE TITLE
Todo Task: Backend

### ISSUE THREAD

**Issue by Sanchitbajaj02** [RCC-MRU/todo-app-backend#27]
- [x] Add task completed and important list
- [x] Fix update todo API
- [x] Fix all parameters and add ?
